"""
Django settings for boss_v1 project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import psycopg2
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
#print(BASE_DIR)

BASE_DIR = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rl)=kdz1u7z4+m*35khwee88!!!@azle3z+l)bc@_h6@r9k2yp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
AD_LOGIN = False

ALLOWED_HOSTS = ["kotak.ahana.technology", "ujjivan.ahana.technology", "jana.ahana.technology", "localhost", "fincare.ahana.technology", "rbl.ahana.technology", "13.68.238.3"]
#ALLOWED_HOSTS = ["*"]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

#ALLOWED_HOSTS = ["kotak.localhost", "jana.localhost", "fincare.localhost", "rbl.localhost", ".localhost", "localhost"]

SESSION_EXPIRE_SECONDS = 900  # 1 min
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_TIMEOUT_REDIRECT = '/logout'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# OTP features
url = "https://www.fast2sms.com/dev/bulkV2"
locker_otp_phone = '9741344071'
headers = {
    'authorization': "ufXkOji7a9JJwzxa10sdPj5I6hAmFWrJQobNANmPWKFMIYF8mDh40128njI2",
    'Content-Type': "application/x-www-form-urlencoded",
    'Cache-Control': "no-cache",
    }

LOG_FILE = os.path.join(BASE_DIR, 'escalation_files/escaltion.log')
REGISTERS_LOG = os.path.join(BASE_DIR, 'registers_log/registers.log')

# Application definition

INSTALLED_APPS = [
    'smuggler',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notifications_app',
    'boss_admin',
    'boss_audit',
    'inward_register',
    'outward_registers',
    'key_movement_registers',
    'branch_document_registers',
    'security_stock_registers',
    'suspense_cash_registers',
    'issuance_registers',
    'security_equipment_registers',
    'petty_cash_register',
    'complaint_registers',
    'gold_loan_registers',
    'fixed_asset_registers',
    'it_asset_registers',
    'tenants'
    
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "tenants.middlewares.TenantMiddleware",
    
]

ROOT_URLCONF = 'boss_v1.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications_app.context_processors.notifications'
            ],
        },
    },
]

WSGI_APPLICATION = 'boss_v1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#   "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": "default.db.sqlite3"},
#   "kotak": {"ENGINE": "django.db.backends.sqlite3", "NAME": "kotak.db.sqlite3"},
#   "jana": {"ENGINE": "django.db.backends.sqlite3", "NAME": "jana.db.sqlite3"},
#   "fincare": {"ENGINE": "django.db.backends.sqlite3", "NAME": "fincare.db.sqlite3"},
#   "rbl": {"ENGINE": "django.db.backends.sqlite3", "NAME": "rbl.db.sqlite3"},

# }

DATABASES = {"default": dj_database_url.config()}
# DATABASES = {
#     "default": {"ENGINE": "django.db.backends.sqlite3", "NAME": "default.db.sqlite3"}
# }

DATABASE_ROUTERS = ["tenants.router.TenantRouter"]

# Escalation Files
REGISTERS_LOG = os.path.join(BASE_DIR, 'registers_log/registers.log')
date_strftime_format = "%d-%b-%Y %H:%M:%S %p"
msg_format = '%(asctime)s :: %(levelname)s :: %(message)s'



# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Calcutta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
CHECKLIST_VISIT_BUFFER_DAYS = 5

# security form request to finance admin

SECURITY_STOCK_EMAIL_SUBJECT = "Requesting for security form"
SECURITY_STOCK_EMAIL_BODY = " Dear Sir/Madam, \n \n     > The following branch {1} has low balance of stock type {0}, Please provide {3} amount of stock type {0}. \n    > Please verify and provide your inputs/approve. \n \n"
SECURITY_STOCK_EMAIL_SIGNATURE = "\n\nThanks, \nJana Small Finance Bank Ltd. \n{}  "
