# Generated by Django 3.1.2 on 2024-05-21 10:43

import boss_admin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('sl_no', models.IntegerField(default=boss_admin.models.BranchMaster.from_500, primary_key=True, serialize=False)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('zone', models.CharField(max_length=100, null=True)),
                ('created_user', models.CharField(max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_user', models.CharField(max_length=150, null=True)),
                ('retention_limit', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'branch_master',
                'ordering': ['sl_no'],
            },
        ),
        migrations.CreateModel(
            name='DesignationMatrix',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('role_type', models.CharField(max_length=250)),
                ('role_name', models.CharField(max_length=250)),
                ('role_code', models.CharField(max_length=250)),
                ('designations', models.JSONField(blank=True, null=True)),
                ('last_modified_user', models.CharField(blank=True, max_length=250, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'designation_matrix',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('sl_no', models.IntegerField(default=boss_admin.models.EmployeeMaster.from_500, primary_key=True, serialize=False)),
                ('domain_id', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('emp_name', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('role', models.IntegerField(null=True)),
                ('created_user', models.CharField(max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('email_id', models.EmailField(max_length=100, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_function', models.CharField(blank=True, max_length=100, null=True)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_user', models.CharField(max_length=150, null=True)),
                ('signature', models.FileField(max_length=500, null=True, upload_to=None)),
                ('branch_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.branchmaster', to_field='branch_code')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_id', to='boss_admin.branchmaster')),
            ],
            options={
                'db_table': 'employee_master',
                'ordering': ['sl_no'],
            },
        ),
        migrations.CreateModel(
            name='PhoneMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.IntegerField()),
                ('isVerified', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'phone_master',
            },
        ),
        migrations.CreateModel(
            name='RegistersMaster',
            fields=[
                ('sl_no', models.IntegerField(default=boss_admin.models.RegistersMaster.from_500)),
                ('registers_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('registers_type', models.CharField(max_length=100, null=True)),
                ('registers_desc', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_user', models.CharField(max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'registers_master',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('ses_id', models.AutoField(primary_key=True, serialize=False)),
                ('ses_key', models.CharField(max_length=200, null=True)),
                ('ses_data', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'session_data',
            },
        ),
        migrations.CreateModel(
            name='RuleSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register', models.CharField(blank=True, max_length=250, null=True)),
                ('rule_type', models.CharField(blank=True, max_length=250, null=True)),
                ('rule_data', models.JSONField(blank=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rulesetup_creator', to='boss_admin.employeemaster', to_field='emp_id')),
                ('modified_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rulesetup_modifier', to='boss_admin.employeemaster', to_field='emp_id')),
            ],
            options={
                'db_table': 'rule_setup_table',
            },
        ),
        migrations.CreateModel(
            name='RegistersRoleMaster',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=150, null=True)),
                ('role_desc', models.CharField(max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_user', models.CharField(max_length=150, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('modified_user', models.CharField(max_length=150, null=True)),
                ('registers_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.registersmaster')),
            ],
            options={
                'db_table': 'registers_role_master',
            },
        ),
        migrations.CreateModel(
            name='PropertyDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('packet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mail_type', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('packet_contents', models.JSONField(null=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('ho_remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('destination_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_branch', to='boss_admin.branchmaster', to_field='branch_code')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.employeemaster', to_field='emp_id')),
                ('source_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_branch', to='boss_admin.branchmaster', to_field='branch_code')),
            ],
            options={
                'db_table': 'property_document_table',
                'ordering': ['packet_id'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_ip', models.CharField(blank=True, max_length=200, null=True)),
                ('in_out', models.DateTimeField(null=True)),
                ('ses_key', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.employeemaster', to_field='emp_id')),
            ],
            options={
                'db_table': 'log_data',
            },
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latittude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('location_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.branchmaster', to_field='branch_code')),
            ],
            options={
                'db_table': 'locationmaster',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRegisterRoleMaster',
            fields=[
                ('emp_reg_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.branchmaster', to_field='branch_code')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_branch_id', to='boss_admin.branchmaster')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigner_emp_id', to='boss_admin.employeemaster', to_field='emp_id')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.employeemaster', to_field='emp_id')),
                ('modified_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_emp_id', to='boss_admin.employeemaster', to_field='emp_id')),
                ('registers_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.registersmaster')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.registersrolemaster')),
            ],
            options={
                'db_table': 'employee_register_role_master',
            },
        ),
        migrations.CreateModel(
            name='BranchVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.branchmaster', to_field='branch_code')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_verify_creator', to='boss_admin.employeemaster', to_field='emp_id')),
                ('modified_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_verify_modifier', to='boss_admin.employeemaster', to_field='emp_id')),
            ],
            options={
                'db_table': 'branch_verification_table',
            },
        ),
        migrations.CreateModel(
            name='AuditorConnectionMaster',
            fields=[
                ('emp_reg_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=150, null=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigner_branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigner_branch', to='boss_admin.branchmaster', to_field='branch_code')),
                ('branch_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_branch', to='boss_admin.branchmaster', to_field='branch_code')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditrole_branch_id', to='boss_admin.branchmaster')),
                ('created_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigner_emp', to='boss_admin.employeemaster', to_field='emp_id')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_audit', to='boss_admin.employeemaster', to_field='emp_id')),
                ('modified_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_modifier_emp', to='boss_admin.employeemaster', to_field='emp_id')),
                ('registers_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.registersmaster')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.registersrolemaster')),
            ],
            options={
                'db_table': 'auditor_connection_master',
            },
        ),
    ]
