# Generated by Django 3.1.2 on 2024-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmaster',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='branchmaster',
            name='state',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='branchmaster',
            name='zone_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
