# Generated by Django 3.1.2 on 2024-06-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boss_admin', '0002_auto_20240522_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationmatrix',
            name='role_dept',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
