# Generated by Django 3.1.2 on 2024-05-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boss_admin', '0002_auto_20240522_1535'),
        ('preliminaryscreeningcommittee_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psctable',
            name='branch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.branchmaster'),
        ),
    ]
