# Generated by Django 3.1.2 on 2024-05-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0002_auto_20240529_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psctable',
            name='branch_code',
            field=models.CharField(max_length=150),
        ),
    ]
