# Generated by Django 3.1.2 on 2024-07-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boss_admin', '0003_designationmatrix_role_dept'),
        ('preliminaryscreeningcommittee_review', '0003_auto_20240529_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psctable',
            name='branch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boss_admin.branchmaster'),
        ),
        migrations.AlterField(
            model_name='psctable',
            name='psc_rec_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('created_user', models.CharField(max_length=150)),
                ('psc_rec_id', models.CharField(max_length=150, unique=True)),
                ('psc_review_id', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('cust_id', models.CharField(max_length=150)),
                ('borrower_name', models.CharField(max_length=150)),
                ('region_name', models.CharField(blank=True, max_length=150, null=True)),
                ('total_exposure', models.CharField(blank=True, max_length=150, null=True)),
                ('acc_count', models.CharField(blank=True, max_length=150, null=True)),
                ('current_role', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('last_modified_user', models.CharField(max_length=150)),
                ('branch_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.branchmaster')),
            ],
            options={
                'db_table': 'customer_table',
            },
        ),
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='psc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preliminaryscreeningcommittee_review.customertable'),
        ),
        migrations.AlterField(
            model_name='securitiestable',
            name='psc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preliminaryscreeningcommittee_review.customertable'),
        ),
    ]
