# Generated by Django 3.1.2 on 2024-08-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0004_auto_20240726_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='review_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customertable',
            name='sac_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customertable',
            name='sac_rec_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customertable',
            name='sac_review_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
