# Generated by Django 3.1.2 on 2024-08-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0005_auto_20240808_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='momtable',
            name='mom_users_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psctable',
            name='psc_users_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sactable',
            name='sac_users_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
