# Generated by Django 3.1.2 on 2024-08-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0006_auto_20240813_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertable',
            name='psc_rec_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
