# Generated by Django 3.1.2 on 2024-10-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0007_auto_20240822_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='npa_status',
            field=models.BooleanField(default=True),
        ),
    ]
