# Generated by Django 3.1.2 on 2024-11-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0008_customertable_npa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditfacilitytable',
            name='cf_aod_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
