# Generated by Django 3.1.2 on 2024-12-19 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0009_creditfacilitytable_cf_aod_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditfacilitytable',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 11, 43, 47, 302538)),
        ),
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='cf_aod_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
