# Generated by Django 3.1.2 on 2025-03-20 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0010_auto_20241219_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 12, 37, 20, 697979)),
        ),
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='npa_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
