# Generated by Django 3.1.2 on 2025-06-23 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0011_auto_20250320_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertable',
            name='lapses_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 23, 15, 25, 9, 362902)),
        ),
    ]
