# Generated by Django 3.1.2 on 2025-09-29 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0012_auto_20250623_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 29, 12, 38, 5, 742415)),
        ),
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='sanctioned_limit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='securitiestable',
            name='insurance_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='securitiestable',
            name='latest_valuation',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='securitiestable',
            name='sanction_valuation',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
