# Generated by Django 3.1.2 on 2026-06-24 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preliminaryscreeningcommittee_review', '0013_auto_20250929_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditfacilitytable',
            name='doc_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 24, 11, 50, 9, 932858)),
        ),
    ]
