# Generated by Django 3.1.2 on 2024-05-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boss_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Sent', 'Sent'), ('Received', 'Received'), ('Approved', 'Approved')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
                ('register_type', models.CharField(max_length=100, null=True)),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('extra_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hyper_link', models.CharField(max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatednotifications', to='boss_admin.employeemaster', to_field='emp_id')),
                ('register_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.registersrolemaster')),
                ('registers_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boss_admin.registersmaster')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='boss_admin.employeemaster', to_field='emp_id')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
