# Generated by Django 3.1.2 on 2024-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Received', 'Received'), ('Sent', 'Sent'), ('Approved', 'Approved')], max_length=30),
        ),
    ]
