# Generated by Django 3.1.2 on 2024-05-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0003_auto_20240522_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Received', 'Received'), ('Sent', 'Sent')], max_length=30),
        ),
    ]
