# Generated by Django 3.1.2 on 2024-07-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0004_auto_20240522_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Sent', 'Sent'), ('Received', 'Received')], max_length=30),
        ),
    ]
