# Generated by Django 3.1.2 on 2026-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0005_auto_20240726_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Received', 'Received'), ('Approved', 'Approved'), ('Sent', 'Sent')], max_length=30),
        ),
    ]
